name: Publish Snapshot

on:
  push:
    branches:
    - branch-1.5

jobs:
  publish-snapshot:
    if: github.repository == 'apache/orc'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1
      with:
        directory: java
        server_id: apache.snapshots.https
        nexus_username: ${{ secrets.NEXUS_USER }}
        nexus_password: ${{ secrets.NEXUS_PW }}
